export const ACTION_TYPES = {
  GET_MOVIES: 'GET_MOVIES',
  SET_MOVIES: 'SET_MOVIES',
  ADD_MOVIE: 'ADD_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  SEARCH_MOVIE: 'SEARCH_MOVIE',
  UPDATE_MOVIE: 'UPDATE_MOVIE'
};

export default ACTION_TYPES;
